version: '3.4'

networks:
   frontend:
   backend:


services:
  catalog:
    image: events1/eventcatalogapi1
    build:
      context: .\EventCatalogAPI
      dockerfile: Dockerfile
    environment: 
      ASPNETCORE_ENVIRONMENT: Development
      DatabaseServer: mssqlserver
      DatabaseName: EventCatalogDb
      DatabaseUser: sa
      DatabasePassword: ProductApi(!) 
      ExternalCatalogUrl: http://localhost:7006
    ports: 
      - "7006:80"
    container_name: eventscatalogapi2
    networks:
      - frontend
      - backend
    depends_on:
      - mssqlserver

  cart:
    image: events1/cartapi
    build:
      context: .\CartApi
      dockerfile: Dockerfile
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ConnectionString: basket.data
      IdentityUrl: http://192.168.86.230:7660
    ports:
      - "7016:80"
    container_name: eventscartapi
    networks:
      - frontend
      - backend
    depends_on:
      - tokenserver
      - basket.data

  order:
    build:
      context: .\OrderApi
      dockerfile: Dockerfile
    image: events1/orderapi
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      IdentityUrl: http://192.168.86.230:7660
      DatabaseServer: mssqlserver
      DatabaseName: OrdersDb
      DatabaseUser: sa
      DatabasePassword: ProductApi(!)
    ports:
      - "7026:80"
    container_name: eventsorderapi
    networks:
      - backend
      - frontend
    depends_on:
      - mssqlserver
      - tokenserver

  webmvc:
    image: events1/webmvc
    build:
      context: .\WebMVC
      dockerfile: Dockerfile
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      EventUrl: http://catalog
      IdentityUrl: http://192.168.86.230:7660
      CallBackUrl: http://localhost:7700
      CartUrl: http://cart
      OrderUrl: http://order
      StripePublicKey: pk_test_51JWbbKDzDKEHkvGhL3u5VnDJvvPsrUWkQnB8pVd3YGE3Qsm2pJ04O2TPTGbE3ylPJzzkbk5IctwjCHs1MXujhFnT00VzBjwZjx
      StripePrivateKey: sk_test_51JWbbKDzDKEHkvGh9T8jb4tMGrIPBuj5Vu7cZO7HhJNDrjDlQtW3txWE0u3mV683OzuyLNBBamkId2IQ6Sf9yaPG00akR1olaC
    ports:
      - "7700:80"
    container_name: eventWebshop
    networks:
      - frontend
    depends_on: 
      - catalog
      - tokenserver
      - cart
      - order

  tokenserver:
    build:
      context: .\TokenServiceApi
      dockerfile: Dockerfile
    image: events/tokenapi
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      MvcClient: http://localhost:7700
    ports:
      - "7660:80"
    container_name: eventstokenserviceapi1
    networks:
      - backend
      - frontend
    depends_on:
      - mssqlserver

  mssqlserver:
    image: "mcr.microsoft.com/mssql/server:latest"
    environment: 
      ACCEPT_EULA: "Y"
      SA_PASSWORD: ProductApi(!)
    ports:
      - "1456:1433"
    container_name: eventssqlserver1
    networks: 
      - backend

  basket.data:
    image: redis
    ports: 
      - "7056:6379"
    container_name: eventsbasketdata1
    networks:
      - backend
